### ISSUE TITLE
levelup / leveldown support

### ISSUE THREAD

**Issue by francescoagati** [Venemo/node-lmdb#115]
actually the support for lmdb on levelup is broken. and lmdb is the only db of leveldb family that support multi core write and read. can be levelup supported?

**Comment by Venemo** [comment]
Hi! I'm unfamiliar with levelup, but if you can explain what it is and what's the benefit, it will be considered.

**Comment by chrbala** [comment]
I'm working on an abstract-leveldown implementation which is almost done - just making the tests pass right now. It's not currently on Github, but if there's interest in helping out, I can publish it.

@Venemo levelup basically provides a consistent API for databases like LMDB. Initially, this was for LevelDB, but there are a number of other database implementations out now. Because all of these provide the same API, it is trivial to swap out one database implementation for another.

**Comment by francescoagati** [comment]
Yes if you can  publish on github i can help you

**Comment by chrbala** [comment]
Okay. I'll get it into a shareable state and push a new repo, probably by EOD tomorrow (Sunday).

**Comment by chrbala** [comment]
I've published [lmdb-leveldown](https://github.com/chrbala/lmdb-leveldown) and created [an issue](https://github.com/chrbala/lmdb-leveldown/issues/1) for the failing tests. There aren't too many issues, so @francescoagati feel free to take a look into them.

**Comment by Venemo** [comment]
Is there anything needed from the `node-lmdb` side?

**Comment by Venemo** [comment]
@francescoagati @chrbala I'm closing this tickets now due to lack of response. If you have any other questions or problems with node-lmdb, feel free to open another issue.
