### ISSUE TITLE
Included LMDB library is not a stable release version

### ISSUE THREAD

**Issue by kriszyp** [Venemo/node-lmdb#140]
The included LMDB library is not a release version of LMDB, it is the master branch with experimental code. In particular, it has experimental use of NTDLL, which we have determined to be source of significant performance, freezing, and instability issues on our servers. node-lmdb should use the stable release branch of lmdb for inclusion.

**Comment by martinvonwittich** [comment]
Is this broken again? I'm using node-lmdb@0.9.7, and `console.log(lmdb.version);` gives me the following output:

```
{
  versionString: 'LMDB 0.9.70: (December 19, 2015)',
  major: 0,
  minor: 9,
  patch: 70
}
```

But the most recently release LMDB version is 0.9.29: https://github.com/LMDB/lmdb/tags

0.9.70 seems to be the version of the master branch. Also, when I'm trying to concurrently read from an LMDB database that is written by a Perl script which uses LMDB 0.9.24, I'm getting an `MDB_VERSION_MISMATCH` error:

```
host nodejs (master) # nodejs lmdb-read.js
{
  versionString: 'LMDB 0.9.70: (December 19, 2015)',
  major: 0,
  minor: 9,
  patch: 70
}
/path/to/nodejs/lmdb-read.js:7
env.open({
    ^

Error: MDB_VERSION_MISMATCH: Database environment version mismatch
    at Object.<anonymous> (/path/to/nodejs/lmdb-read.js:7:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: -30794
}
```

**Comment by kriszyp** [comment]
@martinvonwittich We switched back to the latest 0.9.70 version of LMDB since it ultimately proved to be more stable, performant, and reliable. The "releases" are pretty far behind the stable and reliable versions of LMDB, and missing important functionality.

FWIW, I believe 0.9.70 is actually only incompatible with 0.9.24 in lock files, not data files. So if you are not using Perl and Node concurrently, you might be able to delete the lock file to achieve interoperability (although I could be wrong about that).

**Comment by martinvonwittich** [comment]
@kriszyp thanks for the explanation!

> FWIW, I believe 0.9.70 is actually only incompatible with 0.9.24 in lock files, not data files. So if you are not using Perl and Node concurrently, you might be able to delete the lock file to achieve interoperability (although I could be wrong about that).

Yes, this accurately matches the results I'm getting:

- Reading/writing the database from different languages (I'm currently trying with Perl, Python, PHP, Rust) except NodeJS works fine, even concurrently.
- Reading/writing the database from these languages including NodeJS works fine as long as NodeJS isn't accessing the database concurrently.
- Attempting to read the database from NodeJS while another implementation has locked the database for reading (or writing, but reading is enough to trigger the problem) results in an MDB_VERSION_MISMATCH error in NodeJS.
- Attempting to read the database from one of the other languages while NodeJS has locked the database for reading (haven't tested writing) results in an MDB_VERSION_MISMATCH error in the other implementation.

While I can certainly understand your reasons for using the master branch of LMDB, this does seem like a *major* interoperability pitfall to me. Due to the fact that it only occurs on concurrent accesses, it could result in devious race conditions when attempting to share a LMDB database between NodeJS and other languages. I think a warning about this in the documentation would be very sensible.

**Comment by kriszyp** [comment]
@martinvonwittich Thank you for the research on this, this is very helpful! And I was actually not aware of the lock file incompatibility until you brought this up. And yes, I will update the documentation to make this clear.

I don't think I'd want to create a back-compatibility breakage for node-lmdb itself. However, (as you may know), most of the active development now takes place on [lmdb-js](https://github.com/kriszyp/lmdb-js), where I do actually have a separate build intended for older LMDB and interoperability, and I would be inclined to switch that version to the "release" version for interoperability with other languages' lmdb version.
