### ISSUE TITLE
Blocking beginTransaction for second write transaction

### ISSUE THREAD

**Issue by extern-lukas-zech-zwickroell-com** [Venemo/node-lmdb#164]
I'm currently implementing node-lmdb in a web API setting where one request transports data that will be streamed one of many dbis in one environment.

As each request opens a dbi and begins a transaction to stream its data there may be a situation where another requests tries to write its data while the streaming of an earlier request is not finished.

Therefore the second requests attempts to open a write transaction while the first one is still active.

According to the[ lmdb docs](http://www.lmdb.tech/doc/starting.html#txns) and even the README.md in this very repository, the call to `env.beginTxn` should block until the first write transaction is committed or aborted.

The current behaviour is that an error is thrown as of #88 

This contradicts the documentation and makes it difficult to use node-lmdb for multiple async write approaches.

Would it make sense to make `beginTransaction` return a Promise that resolves with a write transaction as soon as it is valid to create one?
If so I would attempt to implement this and send a PR.

If not, what is the correct solution to this problem? 

1. Make all write attempts synchronious so that there cannot be a second simoultaneous attemp? That is not feasable in an Web API, at least not on the same node process.

2. Manage the write transaction in a singleton service and provide it to each writer? That would mean to keep it alive indefinetly. How to handle commiting/renweing then?

@braydonf You reported #88 and wrote about a async queue to handle this problem [here](https://github.com/Venemo/node-lmdb/issues/68#issuecomment-245804214)
Could you post how you solved this, or if the promise approach I suggested would solve your use case as well?

Thanks

**Comment by kriszyp** [comment]
What error are you getting? Are you running the other transaction in a different process (or thread)? A write `beginTransaction` has always blocked for me when there is another ongoing write transaction _in another process_. And this is the implicit assumption of the documentation as well, it is self-defeating to block a write transaction in the same thread/process as the ongoing transaction since it would block any further execution that would permit the first to finish (and I think lmdb does detect and throw an error for that). And since, normally all JS runs in same thread, you need a second process (or thread, but I don't think node-lmdb supports node worker threads yet) to observe this.

If you want the transaction to run in a _separate thread from your javascript_, this is exactly why the new batchWrite method was introduced:
https://github.com/Venemo/node-lmdb#asynchronous-batched-operations
This _will_ run your transactions in separate threads, and if you use this as the primary way to write data, any blocking will be a separate thread and won't block your JS.

If you are interested in the best strategy for managing different writes and using these separate threaded transactions, I wrote a description of how lmdb-store uses batched writes (with promises) here https://dev.doctorevidence.com/lmdb-in-node-29af907aad6e.

**Comment by Venemo** [comment]
I agree with what Kris said. Also would be useful to see what error you are getting, and maybe give us a small example to reproduce the problem.

**Comment by extern-lukas-zech-zwickroell-com** [comment]
Sorry I linked the wrong PR, I meant to link[ this commit](https://github.com/Venemo/node-lmdb/commit/47ca003b90cb872c59e33b236c5a8ace4684aea8)

The error message is `"You have already opened a write transaction in the current process, can't open a second one."`

I expected that `beginTransaction` would block while another WriteTransaction is active, but of course this only works when called on **another thread or process**

Thanks for your explanation @kriszyp 

I am trying to stream binary data from multiple streams to different dbis in the same environment at the same time. Using one transaction for each chunk is very imperformant but its very complicated to batch chunks of different streams together.

If will have a closer look at https://github.com/DoctorEvidence/lmdb-store

**Comment by extern-lukas-zech-zwickroell-com** [comment]
Just another idea:
would it make sense to have a `beginTransactionAsync ` method that returns a promise which will either resolve immediatelly if no other write transaction is currently active, or resolve as soon as the [current write transaction is unset](https://github.com/Venemo/node-lmdb/blob/master/src/txn.cpp#L46) ?

**Comment by Venemo** [comment]
Pull requests are welcome in that area, if you wish to improve it.
