### ISSUE TITLE
Does node-lmdb support storing live objects?

### ISSUE THREAD

**Issue by hjerabek** [Venemo/node-lmdb#178]
In one of his [presentations about LMDB](https://www.youtube.com/watch?v=tEa5sAh-kVk&feature=youtu.be&t=590), Howard Chu talks about the possibility of storing live objects within an LMDB.

Is this supported by node-lmdb?  
If yes, can I use it to share read access to objects between different Node.js processes/threads without requiring any serialization and deserialization?

**Comment by kriszyp** [comment]
This depends a bit on what you mean, but the short answer is that, no, JavaScript/V8 itself does not support concurrent/shared access to objects, and that doesn't have anything to do with node-lmdb, but rather with the object model of V8 (but that's probably ok).

First, what you _can_ do: you can get a Buffer that points to the shared memory within the LMDB mmap. This is provided by "unsafe" methods like `getBinaryUnsafe`, and it will return a Node Buffer for database entry that can point to the same exact memory location as the buffer that would be returned in another thread or process. You can also use `getStringUnsafe` to get a string that is backed by shared memory. If you really want some low-level excitement, you can turn on useWritemap and you can literally modify that memory and the changes will be visible in another thread/process that is accessing that same memory. Don't actually do this though in any real application, the difficult in synchronizing such interaction would be a nightmare.

However, if we are talking about actual JS objects and data structures this is not possible, and again this is due to the way that JS objects are (necessarily) implemented. In Howard Chu's video, he is basically talking about C struct-based objects that have a fixed, deterministic size and offsets, and can exist in a fixed stable memory location. However, JS objects are extremely dynamic in nature. Every object, sub-object, string, sub-array, etc. is dynamically allocated into locations in memory by V8. Not only that, but their sizes are dynamic as well (V8 team recently wrote about how they use dynamic slack tracking with objects). Objects offsets and size are dynamically handled by the internals of V8. And on top off that, V8 uses copy-based GC, which means that objects don't even stay in a fixed location, but are continually copied to different memory locations. And this can happen in concurrent GC threads as well. All of these are powerful optimizations that has enabled the incredible performance of V8, but also means that it is simply impossible to have any type of direct memory mapping to objects or shared/concurrent access to V8 objects/data structures.

And assuming that this question is ultimately driven by the pursuit of performance, this probably leads to an inevitable conclusion: If serialization and deserialization are essential, it needs be as fast as possible. node-lmdb is an intentionally low-level library, good for delivering binary data, but if you are interested in performance of the entire cycle of db access _and_ (de)serialization, you might want to consider [lmdb-store](https://github.com/DoctorEvidence/lmdb-store) (or [msgpackr](https://github.com/kriszyp/msgpackr) for serialization), which I have worked on in conjunction and extends node-lmdb specifically to offer highly optimized paths (at the native C level) for (de)serialization which provides extremely fast end-to-end storage of objects. And using this, if you have even moderately dynamic data, the performance of V8 + LMDB is probably going to be faster than just about any other DB/language that is available today for storing and interacting with typical objects and data structures.

**Comment by hjerabek** [comment]
1.) Thanks very much for the detailed answer. Even though serialization/deserialization has so far never been a bottleneck in any of my applications/microservices, the premature optimizer within me was curious if LMDB, which already is my "go to" data store, could also help me reduce (de-)serialization.

2.) A few years back, I compared the performance of msgpack-lite to the default JSON (de-)serialization. Since msgpack-lite turned out to be slower, I kept using JSON. If your msgpackr benchmarks are accurate, you must have done a great job at optimizing the (de-)serialization process. Well done!
