### ISSUE TITLE
Modifying unsafe buffers in-place leads to segmentation fault

### ISSUE THREAD

**Issue by hjerabek** [Venemo/node-lmdb#180]
I wanted to use `txn.getBinaryUnsafe` to get data from an LMDB as buffer and modify subparts of it **in-place**. However, every modification operation on that unsafe buffer raises a `Segmentation fault` (Node 12.19.0). I thought that the unsafe, i.e. zero-copy, get method would return a buffer that directly points to the respective part in the virtual memory and would allow me to directly modify the data **in-memory**. Was that a misconception on my side?

**Comment by Venemo** [comment]
> I thought that the unsafe, i.e. zero-copy, get method would return a buffer that directly points to the respective part in the virtual memory

This is correct.

> and would allow me to directly modify the data in-memory

This is not correct. Take a look at the LMDB documentation here: http://www.lmdb.tech/doc/group__mdb.html#ga8bf10cd91d3f3a83a34d04ce6b07992d - the relevant part is this: *The memory pointed to by the returned values is owned by the database. The caller need not dispose of the memory, and may not modify it in any way. For values returned in a read-only transaction any modification attempts will cause a SIGSEGV.*

Hope this helps.

**Comment by kriszyp** [comment]
Venemo is correct, and it is also worth noting that this is because by default the memory maps used the readonly mapped memory. However, if you enable the `useWritemap` flag (`env.open({useWritemap:true})`), the memory maps _are_ writable, and you actually _can_ directly modify the data in-memory. This comes with a tremendous hazards though, since you would be directly modifying the contents of the database.

**Comment by hjerabek** [comment]
Thank you both for the clarifications and additional information.
