### ISSUE TITLE
LMDB file gets created with maximum size when activating useWritemap option

### ISSUE THREAD

**Issue by hjerabek** [Venemo/node-lmdb#188]
When creating an LMDB environment with the `useWritemap:true` option, the resulting memory-mapped file starts of with the size given by `mapSize`, even though it does not contain any data.

Is this behavior to be expected, or could this have something to do with me using an old operating system (Ubuntu 16.04) and Linux kernel (4.15.0-117-generic)?

**Comment by kriszyp** [comment]
I have seen a wide variety of behaviors across different operating systems, including some making the file size the same as the map size, some using disk space corresponding to the map size (even if the file size is reported based on data usage), and some adjusting on the fly. I have also seen problems when an OS does adjust the file size based on data usage on the fly, as performance can suffer due to dynamic disk allocation and fragmentation. So I don't think there is any real expected/guaranteed behavior across OSes (hence the motivation of package controlled file growth like in lmdb-store).

**Comment by hjerabek** [comment]
Thank you for the clarification.
