### ISSUE TITLE
String transactions copy/destructor

### ISSUE THREAD

**Issue by Matt-Esch** [Venemo/node-lmdb#49]
> If you need to use the data later, you will have to copy it for yourself.

How do you recommend copying the strings?

I was hoping there would be a transactional method that would create a transaction, read a string and then close the transaction in the external string resource destructor.

**Comment by Venemo** [comment]
@Matt-Esch You couldn't close the transaction in the external string resource destructor because that would lead to unintuitive behaviour.

If you want to use strings (or buffers), either keep the transaction open for as long as you need to use them, or copy them. Take a look at this: https://github.com/Venemo/node-lmdb/issues/32

**Comment by Matt-Esch** [comment]
> That would lead to unintuitive behavior

Perhaps. I am using LMDB to index a large collection of translation strings from a read-only database. I was hoping to make use of the zero-copy property of LMDB to avoid string copies, but I don't know how long the string lives for other than it is a finite amount of time in the order of seconds (typical request cycle). A GC hooked transaction would be nice in this use case.

Buffers in node use the GC hooks to free memory, and I see a transaction as an external alloc.

**Comment by Venemo** [comment]
You know exactly how long the string lives: until you close the transaction with which you read it. (Meaning either commit or abort.) The memory in which they reside is owned by LMDB and is only guaranteed to be intact while you keep the transaction open.

If you need your strings for a longer time than that, you can copy them using one of the ways described above.

However since you are not the only one to ask about this, I might consider adding an API to node-lmdb that does the copying for you.
