### ISSUE TITLE
Return 'undefined' instead of null when key not found.

### ISSUE THREAD

**Issue by NodeGuy** [Venemo/node-lmdb#97]
Currently the getters return `null` when the requested key isn't present.  Returning `undefined` instead of `null` would match the behavior of `Map`'s `get` and thus be more idiomatic:

### 23.1.3.6 Map.prototype.get ( key )

> The following steps are taken:
> 
> 1. Let M be the this value.
> 2. If Type(M) is not Object, throw a TypeError exception.
> 3. If M does not have a [[MapData]] internal slot, throw a TypeError exception.
> 4. Let entries be the List that is the value of M’s [[MapData]] internal slot.
> 5. Repeat for each Record {[[key]], [[value]]} p that is an element of entries,
> 6. If p.[[key]] is not empty and SameValueZero(p.[[key]], key) is true, return p.[[value]].
> 7. Return `undefined`.

http://www.ecma-international.org/ecma-262/6.0/#sec-map.prototype.get

**Comment by Venemo** [comment]
What exactly would be the benefit of returning `undefined` instead of `null`? Right now, changing `null` to `undefined` would be a breaking change to all existing users.

Also, unfortunately, the `undefined` keyword in JavaScript has some bad history, see for example [this StackOverflow question](http://stackoverflow.com/questions/8783510/how-dangerous-is-it-in-javascript-really-to-assume-undefined-is-not-overwritte). I know that these issues are all fixed in ES6, but then again, I don't see the benefit of changing this behaviour at this time (also, older node versions still use ES5).

**Comment by NodeGuy** [comment]
Thank you for entertaining my suggestion.  The benefit is that it will save time for programmers to use the library by leveraging what they already know, e.g., I was inspired to write this issue after I had to go into the C code of this library to figure out what happens when the key doesn't exist.

Another way to achieve this is to document better the behavior of the getter functions if you're concerned about making a breaking change.

It's not important to me if you think the benefit isn't worth the cost.

**Comment by Venemo** [comment]
@NodeGuy Here's my real problem with `undefined`:

```
(function(undefined) { console.log(undefined); })("Hello world");
```

**Comment by NodeGuy** [comment]
Ha, that's surprising!
