### ISSUE TITLE
Make transactions read-only by default.

### ISSUE THREAD

**Issue by NodeGuy** [Venemo/node-lmdb#98]
Read-only transactions are safer so it should require less effort when creating them and more effort when making potentially dangerous transactions.

**Comment by da77a** [comment]
Why are read-only transactions "safe" and write transactions "potentially dangerous"? Currently node-lmdb exposes the underlying lmdb definition of a transaction. The semantics of an lmdb transaction are well specified. Assuming that you mean that any transactions that modify the content of a database are _potentially dangerous_ _writes_ this implies a _read only_ transaction type that does not have _del_ and _put*_ methods. Presumably _cursor.del_ would also be hidden/disallowed in a cursor constructed with a "read only" transaction. What would this achieve other than complicating the interface? If you don't want to do a "dangerous" _del_ or _put_ don't call _del_ or _put_. Simple?

Note that all transactions are _dangerous_ in some way because leaving a _write_ pending prevents any further writes until/unless the transaction completes while leaving any transaction open keeps a snapshot of the database alive (which, if the database is being actively written/updated in other transactions may cause a substantial growth in the size of the database while such a _read_ transaction remains open). All transactions need to be short for lmdb to perform well.

**Comment by Venemo** [comment]
You can open a read-only transaction like this:

```
var txn1 = env.beginTxn({ readOnly: true });
```

**Comment by Venemo** [comment]
@NodeGuy Also, what exactly would be the benefit of the proposed change? At this time, this would be a breaking change for all existing users.

**Comment by NodeGuy** [comment]
The benefit would have been avoiding accidental writes but it's not that important to me, thank you for your consideration.

**Comment by Venemo** [comment]
@NodeGuy I might consider this next time there is a major API redesign, but right now this would be a breaking change for everyone, and as such, isn't worth the effort. Thank you for your suggestion!
